shader_type canvas_item;


uniform float y_rot : hint_range(-360.0, 360.0) = 0.0;
uniform float x_rot : hint_range(-360.0, 360.0) = 0.0;


varying flat vec2 o;
varying vec3 p;
uniform sampler2D dissolve_texture : source_color;
uniform float dissolve_value : hint_range(0,1);
uniform float burn_size: hint_range(0.0, 1.0, 0.01);
uniform vec4 ash_color: source_color = vec4(0,0,0,1.0);
uniform vec4 burn_color: source_color;
uniform vec4 proburn_color: source_color = vec4(0.804, 0.2, 0.093 , 1.0);

// Creates rotation matrix
void vertex(){
	float sin_b = sin(y_rot / 180.0 * PI);
	float cos_b = cos(y_rot / 180.0 * PI);
	float sin_c = sin(x_rot / 180.0 * PI);
	float cos_c = cos(x_rot / 180.0 * PI);
	
	mat3 inv_rot_mat;
	inv_rot_mat[0][0] = cos_b;
	inv_rot_mat[0][1] = 0.0;
	inv_rot_mat[0][2] = -sin_b;
	
	inv_rot_mat[1][0] = sin_b * sin_c;
	inv_rot_mat[1][1] = cos_c;
	inv_rot_mat[1][2] = cos_b * sin_c;
	
	inv_rot_mat[2][0] = sin_b * cos_c;
	inv_rot_mat[2][1] = -sin_c;
	inv_rot_mat[2][2] = cos_b * cos_c;
	
	
	float t = tan(25.0 / 360.0 * PI);
	p = inv_rot_mat * vec3((UV - 0.5), 0.5 / t);
	float v = (0.5 / t) + 0.5;
	p.xy *= v * inv_rot_mat[2].z;
	o = v * inv_rot_mat[2].xy;

	VERTEX += (UV - 0.5);
}

void fragment(){
	vec2 uv = (p.xy / p.z).xy - o;

	vec4 main_texture = texture(TEXTURE, (uv / 1.2) + 0.5);
	vec4 noise_texture = texture(dissolve_texture, uv + 0.5);
	
	COLOR = main_texture;
	//COLOR.a *= step(max(abs(uv.x), abs(uv.y)), 0.5);
	
	// This is needed to avoid keeping a small burn_color dot with dissolve being 0 or 1
	// is there another way to do it?
	float burn_size_step = burn_size * step(0.001, dissolve_value) * step(dissolve_value, 0.999);
	float threshold = smoothstep(noise_texture.x-burn_size_step, noise_texture.x, dissolve_value);
	float border = smoothstep(noise_texture.x, noise_texture.x + burn_size_step, dissolve_value);
	
	
	
	vec3 new_burn_color1 = mix(proburn_color.rgb , burn_color.rgb , 1.0-pow(1.0-border , 5));
	vec3 new_burn_color2 = mix(ash_color.rgb , new_burn_color1 , 1.0-pow(1.0-border , 1000));
	COLOR.rgb = mix(new_burn_color2, main_texture.rgb, border);
	COLOR.a *= threshold;
}

void light() {
    // 1. Get the normal contribution of the current light
    vec4 current_light = LIGHT_COLOR * LIGHT_ENERGY;
    
    // 2. Add it to the existing accumulated light
    vec4 total_light = clamp(LIGHT + current_light, 0.0, 1.0);
    
    // 3. Cap the maximum value (e.g., maximum brightness of 1.0)
    // You can adjust vec4(1.0) to lower values like vec4(0.8) for dimmer maximums
    LIGHT = total_light * COLOR;
}
